# Generated by Django 4.1.7 on 2023-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(related_name='news', to='core.writer'),
        ),
    ]
