# Generated by Django 4.1.7 on 2023-03-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_news_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('header', models.CharField(blank=True, max_length=100, verbose_name='Заглавие статьи')),
                ('article', models.TextField(blank=True, verbose_name='Статья')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
